# Generated by Django 4.0.3 on 2022-03-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_remove_curso_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
